<h3 class="text-left">Formulario de Exemplo</h3>
<?= $form->openTag()?>
<?= $form->getField('contato')->openTag()?>
<h5 class="text-info">Nome</h5>
<?=$form->getField('contato')->getField('nome')->render()?>
<h5 class="text-info">Valor</h5>
<?=$form->getField('contato')->getField('valor')->render()?>
<h5 class="text-info">Descrição</h5>
<?=$form->getField('contato')->getField('descricao')->render()?>
<h5 class="text-info">Categoria</h5>
<?=$form->getField('contato')->getField('categoria')->render()?>
<br /><br />
<?= $form->getField('contato')->getField('enviar')->render()?>
<?= $form->getField('contato')->closeTag()?>
<?=$form->closeTag()?>
<?= $helper->htmlList($messages)?>
