<h3 class="text-left">Formulario de Exemplo</h3>
<?= $form->openTag()?>
<h5 class="text-info">Nome</h5>
<?=$form->render('nome')?>
<h5 class="text-info">Valor</h5>
<?=$form->render('valor')?>
<h5 class="text-info">Descrição</h5>
<?=$form->render('descricao')?>
<h5 class="text-info">Categoria</h5>
<?=$form->render('categoria')?>
<br /><br />
<?= $form->render('enviar')?>
<?=$form->closeTag()?>
<?= $helper->htmlList($messages)?>
